### PR TITLE
proper scm icons

### PR DESCRIPTION
**Pull request by fleg**
git: 
screenshot from 2016-03-17 23_10_52

hg:
screenshot from 2016-03-17 23_11_58

### CODE REVIEW

**Comment by okv** [comment]
:+1:

**Comment by okv** [comment]
I found that scmicons font have wrong paddings because of that icon not vertically aligned.
Is it possible to fix? On your screenshots you can compare vertical alignment with icon near "Build history" (which is correct).

**Comment by fleg** [comment]
> Is it possible to fix?

I investigate that

**Comment by artzhookov** [comment]
It's not a good idea to use "vertical-align: middle" because you may need another vertical align. Fontawesome does not specify it and I think you should use similar styles here. This problem should be fixed by rebuilding font files with additional vertical spaces inside of font.

**Comment by fleg** [comment]
In scmicons@1.3.0 vertical-align removed

**Pull request merged**
